### ISSUE TITLE
dataset shape is very strange

### ISSUE THREAD

**Issue by bogeyixiu** [HasnainRaz/SemSegPipeline#14]
Thank you very much for your sharing. I used your code to load the dataset, but found that the generated dataset shape is very strange, as shown below: 
![image](https://github.com/HasnainRaz/SemSegPipeline/assets/96643049/fa720e62-cc46-4bfc-a279-f94aec619917)

If you see it, I hope you can answer it at your convenience. Thank you

**Comment by HasnainRaz** [comment]
@bogeyixiu Last time I used tensorflow was when this repo was created. So I remember back then this was normal, as tensorflow creates a graph and doesn't know what the shape of the objects will be as that cannot be implicitly inferred. Actually executing the pipeline and checking the images it yields you can confirm the shape is correct.

I this behavior has changed in tensorflow, then I'm prolly too outdated to help.
