### ISSUE TITLE
data augmentation with tf.data.map

### ISSUE THREAD

**Issue by lukk47** [HasnainRaz/SemSegPipeline#2]
Can we do the data augmentation with the map function?
It seems no more arguments about the augmentation can be feed the _parse_data function.

**Comment by HasnainRaz** [comment]
Hey, I just updated the code with a newer augmentation pipeline. I have defined the range of random transformations inside each function, so there's no need to pass them in explicitly, you could modify those values if you like, or optionally, you could try if this works, I'm not really sure:
```python
tf.data.map(lambda: your_augmentation_function(param1, param2, ..., paramN))
```

**Comment by lukk47** [comment]
I would like to have additional arguments for using each augmentation method selectively. I just realized it could also be accomplished by selectively using the map function. Thanks for sharing.

**Comment by HasnainRaz** [comment]
Yes, that's the plan for a future change, a parameter dict that defines which augmentations to apply, which to turn off, along with their ranges.
