### ISSUE TITLE
Multiple outputs, one input

### ISSUE THREAD

**Issue by ntelo007** [HasnainRaz/SemSegPipeline#8]
Hi, thank you for your work! It looks a really nice and simple data loading pipeline. Could you please make modifications in order for your script to return 3 masks (in case of having more than just one output). In my case, I only have 1 input, but it would also be nice to give the option for both multiple inputs and outputs.

Thank you in advance.

**Comment by HasnainRaz** [comment]
Thank you for the comments and ideas. I want to keep this as general as possible, to extend it to multiple outputs, have a look here:

https://github.com/HasnainRaz/SemSegPipeline/issues/6

This might lead you in the right direction.
